Onlinejobportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('adminmodule.urls')),
    path('jobseeker/',include('jobseekermodule.urls')),
    path('employer/',include('employermodule.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminmodule/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.projecthomepage, name = 'projecthomepage'),
    path('employeerhomepage', views.employeerhomepage, name = 'employeerhomepage'),
    path('jobseekerhomepage',views.jobseekerhomepage, name = 'jobseekerhomepage'),
    path('signup', views.signup, name = 'signup'),
    path('signup1', views.signup1, name = 'signup1'),
    path('login', views.login, name='login'),
    path('login1', views.login1, name='login1'),
    path('logout', views.logout, name='logout'),
]

employermodule/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'employermodule'
urlpatterns = [
    path('jobpost/',views.jobpost,name='jobpost'),
    path('add_job_details',views.add_job_details,name='add_job_details'),
    path('view/',views.view_job_details,name='view_job_details'),
    path('edit/<int:job_id>/',views.edit_job_details,name='edit_job_details'),
    path('delete/<int:job_id>/',views.delete_job_details,name='delete_job_details'),
    path('job_application_list/',views.job_application_list,name='job_application_list'),
]

jobseekermodule/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'jobseekermodule'
urlpatterns = [
    path('viewjobs',views.viewjobs,name='viewjobs'),
    path('job_details_list',views.job_details_list,name='job_details_list'),
    path('submit_form/',views.submit_form,name='submit_form'),
    path('addjobseekerprofile/',views.addjobseekerprofile,name='addjobseekerprofile'),
    path('apply/<int:job_id>/',views.apply_to_job,name='apply_to_job'),

]








if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Navbar/employernavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color:#FF671F">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">KL Job Portal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-weight: bold">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/employeerhomepage">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'employermodule:jobpost' %}">Job Post</a>
        </li>
                <li class="nav-item">
          <a class="nav-link" href="{% url 'employermodule:view_job_details' %}">View Jobs</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'employermodule:job_application_list' %}">View Job Applications</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
              <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
<!--      <ul class = "navbar-nav ms-auto">-->
<!--              <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'employeerhomepage' %}">Employer</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'jobseekerhomepage' %}">Job Seeker</a>-->
<!--        </li>-->
<!--      </ul>-->
      <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
    </div>
  </div>
</nav>
{% block body %}

{% endblock %}
<footer id ="sticky-footer" class="flex-shrink-0 py-2">
  <div class = "container text-center">
    <small> Copyright &copy; Dr. Deepak. V - K L University. All rights reserved</small>
  </div>
</footer>
<style>
  #sticky-footer {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: #046A38;
    color: white;
    padding: 10px;
    font-weight: bold;
  }
</style>
</body>
</html>

templates/Navbar/jobseekernavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color:#FF671F">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">KL Job Portal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-weight: bold">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'projecthomepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'jobseekermodule:addjobseekerprofile' %}">Profile</a>
        </li>
                <li class="nav-item">
          <a class="nav-link" href="{% url 'jobseekermodule:job_details_list' %}">View Jobs</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
              <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
<!--      <ul class = "navbar-nav ms-auto">-->
<!--              <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'employeerhomepage' %}">Employer</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'jobseekerhomepage' %}">Job Seeker</a>-->
<!--        </li>-->
<!--      </ul>-->
      <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
    </div>
  </div>
</nav>
{% block body %}

{% endblock %}
<footer id ="sticky-footer" class="flex-shrink-0 py-2">
  <div class = "container text-center">
    <small> Copyright &copy; Dr. Deepak. V - K L University. All rights reserved</small>
  </div>
</footer>
<style>
  #sticky-footer {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: #046A38;
    color: white;
    padding: 10px;
    font-weight: bold;
  }
</style>
</body>
</html>

templates/Navbar/projectnavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color:#FF671F">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">KL Job Portal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-weight: bold">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'projecthomepage' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
              <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
<!--      <ul class = "navbar-nav ms-auto">-->
<!--              <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'employeerhomepage' %}">Employer</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'jobseekerhomepage' %}">Job Seeker</a>-->
<!--        </li>-->
<!--      </ul>-->
<ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>

    </div>
  </div>
</nav>
{% block body %}

{% endblock %}
<footer id ="sticky-footer" class="flex-shrink-0 py-2">
  <div class = "container text-center">
    <small> Copyright &copy; Dr. Deepak. V - K L University. All rights reserved</small>
  </div>
</footer>
<style>
  #sticky-footer {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: #046A38;
    color: white;
    padding: 10px;
    font-weight: bold;
  }
</style>
</body>
</html>